[package]
name = "rrot"
version = "0.1.0"
authors = ["nikto_b <niktob560@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
